# 2019-11-18 SAROGN 

kglid  = {
            # Known Receivers
           "NONE"   : "None",
           "LELT"   : "Lillo, Toledo",
           "LEOC"   : "Ocana, Toledo",
           "LECI1"  : "Santa Cilia de Jaca, Huesca",
           "LECI2"  : "San Juan de la Pena, Huesca",
           "LEFM"   : "Fuentemilanos, Segovia",
           "LERM"   : "Robledillo de Mohernando",
           "PWLERM" : "Robledillo de Mohernando",
           "CREAL"  : "Ciudad Real",
           "MORA"   : "Mora de Toledo, Toledo",
           "MADRID" : "Madrid - Test site",
           "LEMD"   : "Madrid - Test site",
           "LETP"   : "Santo Tome del Puerto, Segovia",
           "LEIG"   : "Igualada, Barcelona ",
           "LECD"   : "La Cerdanya, Girona ",
 	   "LESU"   : "La Seu de Urgel, Lerida ",
           "ANDORRA": "Andorra ",
           "TOSA"   : "La TOSA de Alp, Girona ",
           "LAMOLINA" : "La TOSA de Alp, Girona ",
           "ALCAZAREN" : "Alcazaren, Valladolid ",
           "AVILA"  : "Avila ",
           "PORTAINE":"PortAine Ski station ",
           "STOROSIAW":"Santa Orosia, Huesca ",
           "STOROE":"Santa Orosia, Huesca ",
           "STOROW":"Santa Orosia, Huesca ",
           "STOROSIAE":"Santa Orosia, Huesca ",
           "PALOE"   : "Palo, Huesca ",
           "PALOW"   : "Palo, Huesca ",
           "BOITAULL" : "Boi Taull, Lerida ",
           "TorDelOri" : "Torre del Orri, Lerida ",
           "TORDELORI" : "Torre del Orri, Lerida ",
           "CASTEJONS" : "Castejon de Saoa, Huesca ",
           "FONTROMEU" : "FontRomeu, France ",
           "LFCO"   : "Oloron",
           "LFDT"   : "Tarbes",
           "LFIM"   : "Saint Gaudens",
           "LFNW"   : "Puivert",
           "LFNQ"   : "Mount-Louis",
           "LFNQ2"  : "Mount-Louis",
           "LFDH"   : "Auch",
           "LFID"   : "Condom/Valence",
           "LFCN"   : "Novaro",
           "LFIT"   : "Toulouse Bourg",
           "LFCB"   : "Bagneres de Luchon",
           "LFCQ"   : "Graulhet",
           "LFNB"   : "Mende",
           "LFNE"   : "Salon Eyguires",
           "LFNL"   : "Saint Martin",
 	   "LFNZ"   : "Romanin-Saint Remy",
	   "LFNT"   : "Avignon-Pujaut ", 
	   "LFCX"   : "Moissac ", 
	   "LFCG"   : "Saint Girons", 
	   "LFCH"   : "Arcachon", 
	   "LFMP"   : "Perpignan", 
	   "LFCS"   : "Bordeaux", 
	   "LFMG"   : "La Montagne Noir", 
	   "LFMP"   : "Perpignan", 
           "PAU"    : "Pau",
           "ROCAUDE": "Les Angles Ski Station",
           "POUBEAU": "Pou Beau, France",
	   "BRAM"   : "Puivert test",
           "CARCA"  : "Carcassone, France",
           "ROQUEFORT"  : "Roquefort, France",
           "SCLC"   : "Vitacura Municipal ",
           "SCVH"   : "Chacabuco Municipal ",
           "VITACURA1" : "Vitacura - 1 ",
           "VITACURA2" : "Vitacura - 2 ",
           "COLORADO" : "Colorado ski resort  ",
           "WBUXTON"  : "Chicureo area - 1 ",
           "WBUXTON2" : "Chicureo area - 2 ",
           "ROBLE1" : "El Roble hill - 1",
           "ROBLE2" : "El Roble hill - 2",
           "ROBLE3" : "El Roble hill - 3",
           "ROBLE4" : "El Roble hill - 4",
           "LOSANDES1" : "Los andes area - 1 ",
           "LOSANDES2" : "Los andes area - 2 ",
           "TROCALAN1" : "Trocalan hill - 1", 
           "TROCALAN2" : "Trocalan hill - 2", 
           "PoloCL" : "Polo field",
           "ELBOSQUE1" : "El Bosque Airfield",
           "ELBOSQUE2" : "El Bosque Airfield",
           "ALFALFAL" : "Alfalfal hidroelectic plant",
           "PUNTILLA" : "Alfalfal hill",
           "SANRAMON1": "San Ramon Mountain 1",
           "SANRAMON2": "San Ramon Mountain 2",
           "SANRAMON3": "San Ramon Mountain 3",
           "OLMUE": "OLMUE Airfield",
#           # list on known gliders
           "DDE3E3" : "EC-JYS",
###############################
# OGN      data
# FLARMNET data
#######################
	}
