
# 2020-08-05 CASADOUBUNTU
ksta = { 
# -------------------------------------------------------------------#
# Known Receivers
           "NONE"   : "None",
# Spanish airports
           "LELT"   : "Lillo, Toledo",
           "LEOC"   : "Ocana, Toledo",
           "LECI1"  : "Santa Cilia de Jaca, Huesca",
           "LECI2"  : "San Juan de la Pena, Huesca",
           "LENA"   : "Benabarre, Huesca",
           "LEFM"   : "Fuentemilanos, Segovia",
           "LERM"   : "Robledillo de Mohernando, Guadalajara",
           "LEMD"   : "Madrid - Test site",
           "LEMDADSB"   : "Madrid - ADSB GateWay",
           "LETP"   : "Santo Tome del Puerto, Segovia",
           "LEIG"   : "Igualada, Barcelona ",
           "LECD"   : "La Cerdanya, Girona ",
 	   "LESU"   : "La Seu de Urgel, Lerida ",
 	   "LEGY"   : "Garray, Soria ",
 	   "LEPA1"  : "Palma de Mallorca, Baleares ",
 	   "LETC"   : "Matilla de los Caños, Valladolid ",
           "PWLERM" : "Robledillo de Mohernando",
           "ALCAZAREN" : "Alcazaren, Valladolid ",
           "ANDORRA": "Andorra ",
           "AVILA"  : "Avila ",
           "CASTEJONS" : "Castejon de Sos, Huesca ",
           "CREAL"  : "Ciudad Real",
           "LAMOLINA" : "La TOSA de Alp, Girona ",
           "LUGO"   : "Lugo ",
           "MORA"   : "Mora de Toledo, Toledo",
           "MADRID" : "Madrid - Test site",
           "MATARO" : "Mataro, Barcelona ",
           "PWMATARO" : "Mataro, Barcelona ",
           "PORTAINE":"PortAine Ski station ",
           "STOROE" :"Santa Orosia, Huesca ",
           "STOROW" :"Santa Orosia, Huesca ",
           "TAULL2" : "Boi Taull ski station, Lerida ",
           "Taull2" : "Boi Taull ski station, Lerida ",
           "BOITAULL" : "Boi Taull, Lerida ",
           "ALDEASEST" : "Aldea de San Estaban, Soria ",
           "AldeaSEst" : "Aldea de San Estaban, Soria ",
           "MADRUEDAN" : "Madruedano, Soria ",
           "Madruedan" : "Madruedano, Soria ",
           "SMUERDO" : "Sierra de Muerdo, Soria ",
           "SMuerdo" : "Sierra de Muerdo, Soria ",
           "PCARRASCO" : "Puerto de la Carrascosa, Soria ",
           "PCarrasco" : "Puerto de la Carrascosa, Soria ",
           "SSalvador" : "San Salvador, el Cuculo, Huesca ",
           "SSALVADOR" : "San Salvador, el Cuculo, Huesca ",
           "RACE"      : "Race in Cuatro Vuentos, Madrid ",
           "PWRACE"    : "Race in Cuatro Vuentos, Madrid ",
# french airports
           "LFBM"   : "Mont de Marsan",
	   "LFBA"   : "La Garomme", 
	   "LFBS"   : "Biscarrosse", 
           "LFCO"   : "Oloron",
	   "LFCX"   : "Moissac ", 
	   "LFCG"   : "Saint Girons", 
	   "LFCH"   : "Arcachon", 
           "LFCB"   : "Bagneres de Luchon",
           "LFCQ"   : "Graulhet",
	   "LFCS"   : "Bordeaux", 
           "LFDT"   : "Tarbes",
           "LFDA"   : "Air sur Adour",
           "LFDH"   : "Auch",
           "LFDT2"  : "Tarbes",
           "LFIM"   : "Saint Gaudens",
           "LFNW"   : "Puivert",
           "LFNQ"   : "Mount-Louis",
           "LFNQ2"  : "Mount-Louis",
           "LFDHTWR": "Auch",
           "LFID"   : "Condom/Valence",
           "LFCN"   : "Novaro",
           "LFIT"   : "Toulouse Bourg",
           "LFIL"   : "Rion des Landes",
           "LFNB"   : "Mende",
           "LFNE"   : "Salon Eyguires",
           "LFNL"   : "Saint Martin",
 	   "LFNZ"   : "Romanin-Saint Remy",
	   "LFNT"   : "Avignon-Pujaut ", 
	   "LFMP"   : "Perpignan", 
	   "LFMG"   : "La Montagne Noir", 
	   "LFMP"   : "Perpignan", 
	   "LFIX"   : "Itxassou", 
           "LFLE"   : "Challes les Eaux", 
           "PAU"    : "Pau",
           "ROCAUDE": "Les Angles Ski Station",
           "POUBEAU": "Pou Beau, France",
	   "BRAM"   : "Puivert test",
           "CARCA"  : "Carcassone, France",
           "ROQUEFORT" : "Roquefort, France",
           "Roquefort" : "Roquefort, France",
           "FONTROMEU" : "FontRomeu, France ",
           "FontRomeu" : "FontRomeu, France ",
# Portuguese airports
           "LPCB"      : "Castelo Branco",
           "LPMU"      : "Modadouro ",
           "LPLZ"      : "Lousa",
           "LPMN"      : "Amondoeira",
           "LPEV"      : "Evora",
           "BELAVISTA" : "Belavista, Lisbon ",
# Chilean airports 
           "SCLC"      : "Vitacura Municipal ",
           "SCVH"      : "Chacabuco Municipal ",
           "VITACURA1" : "Vitacura - 1 ",
           "VITACURA2" : "Vitacura - 2 ",
           "COLORADO"  : "Colorado ski resort  ",
           "WBUXTON"   : "Chicureo area - 1 ",
           "WBUXTON2"  : "Chicureo area - 2 ",
           "ROBLE1"    : "El Roble hill - 1",
           "ROBLE2"    : "El Roble hill - 2",
           "ROBLE3"    : "El Roble hill - 3",
           "ROBLE4"    : "El Roble hill - 4",
           "LOSANDES1" : "Los andes area - 1 ",
           "LOSANDES2" : "Los andes area - 2 ",
           "TROCALAN1" : "Trocalan hill - 1", 
           "TROCALAN2" : "Trocalan hill - 2", 
           "PoloCL"    : "Polo field",
           "ELBOSQUE1" : "El Bosque Airfield",
           "ELBOSQUE2" : "El Bosque Airfield",
           "ALFALFAL"  : "Alfalfal hidroelectic plant",
           "PUNTILLA"  : "Alfalfal hill",
           "SANRAMON1" : "San Ramon Mountain 1",
           "SANRAMON2" : "San Ramon Mountain 2",
           "SANRAMON3" : "San Ramon Mountain 3",
           "OLMUE"     : "OLMUE Airfield",
# -------------------------------------------------------------------#
# ------------------------------------------------------------------ #
	}
# -------------------------------------------------------------------#
