
# 2020-08-05 CASADOUBUNTU
ksta = { 
# -------------------------------------------------------------------#
# Known Receivers
           "NONE"   : "None",
# Spanish airports
"LELT"   : "Lillo, Toledo",
"LEOC"   : "Ocana, Toledo",
"LECI1"  : "Santa Cilia de Jaca, Huesca",
"LECI2"  : "San Juan de la Pena, Huesca",
"LENA"   : "Benabarre, Huesca",
"LEFM"   : "Fuentemilanos, Segovia",
"LERM"   : "Robledillo de Mohernando, Guadalajara",
"LERM2"  : "Robledillo de Mohernando, Guadalajara",
"LEMD"   : "Madrid - Test site",
"LETP"   : "Santo Tome del Puerto, Segovia",
"LEIG"   : "Igualada, Barcelona ",
"LEIG2"  : "Igualada, Barcelona ",
"LECD"   : "La Cerdanya, Girona ",
"LESU"   : "La Seu de Urgel, Lerida ",
"LERO"   : "Rozas, Lugo ",
"LEGY"   : "Garray, Soria ",
"LELL"   : "Sabadell, Barcelona ",
"LEIS"   : "Binisalem, Palama ",
"LEPA1"  : "Palma de Mallorca, Baleares ",
"LETC"   : "Matilla de los Caños, Valladolid ",
"LEGA"   : "Armilla AB, Granada ",
"LERE"   : "Requena, Valencia",
"LETL"   : "Teruel, Teruel",
"LEMT"   : "Casarrubios del Monte, Madrid",
"LECU"   : "Cuatro Vientos",
"LEMU"   : "Mutxamiel, Alicante",
"LEBE"   : "Beas del Segura, Jaen",
"LEDE"   : "Cordoba",
"LEMS"   : "Manresa",
"LECA"   : "Corral de Ayllon",
"LEZS"   : "Chozas, Leon",
"LEMR"   : "La Morgali, Asturias",
"LEPN"   : "Valverde de Leganes, Badajoz",
"LEVT"   : "Vitoria",
"LETX"   : "Totana, Murcia",
"LETI"   : "El Tietar, Toledo",
"LECN"   : "Castellon de la Plana",
"LERS"   : "Reus, Tarragona",
#
# spanish sites
"LEMDADSB"  : "Madrid - ADSB GateWay",
"LEMDTEST"  : "Madrid - ADSB Test",
"PWLERM2"   : "Robledillo de Mohernando",
"ALCAZAREN" : "Alcazaren, Valladolid ",
"ANDORRA"   : "Andorra ",
"Avila"     : "Avila ",
"AVILA"     : "Avila ",
"CASTEJONS" : "Castejon de Sos, Huesca ",
"CREAL"     : "Ciudad Real",
"CReal"     : "Ciudad Real",
"LAMOLINA"  : "La TOSA de Alp, Girona ",
"LUGO"      : "Lugo ",
"MORA"      : "Mora de Toledo, Toledo",
"MADRID"    : "Madrid - Test site",
"MATARO"    : "Mataro, Barcelona ",
"PWMATARO"  : "Mataro, Barcelona ",
"PORTAINE"  :"PortAine Ski station ",
"STOROE"    :"Santa Orosia, Huesca ",
"STOROW"    :"Santa Orosia, Huesca ",
"TAULL2"    : "Boi Taull ski station, Lerida ",
"Taull2"    : "Boi Taull ski station, Lerida ",
"BOITAULL"  : "Boi Taull, Lerida ",
"ALDEASEST" : "Aldea de San Estaban, Soria ",
"AldeaSEst" : "Aldea de San Estaban, Soria ",
"MADRUEDAN" : "Madruedano, Soria ",
"Madruedan" : "Madruedano, Soria ",
"SMUERDO"   : "Sierra de Muerdo, Soria ",
"SMuerdo"   : "Sierra de Muerdo, Soria ",
"PCARRASCO" : "Puerto de la Carrascosa, Soria ",
"PCarrasco" : "Puerto de la Carrascosa, Soria ",
"SpainSun"  : "Station with Solar Panels, Soria ",
"SPAINSUN"  : "Station with Solar Panels, Soria ",
"Oncala"    : "Puerto de Oncala, Soria ",
"ONCALA"    : "Puerto de Oncala, Soria ",
"Duruelo"   : "Duruelo de la Sierra , Soria ",
"DURUELO"   : "Duruelo de la Sierra , Soria ",
"ONCALA"    : "Oncala , Soria ",
"Oncala"    : "Oncala , Soria ",
"Medinacel" : "Medinaceli , Soria ",
"MEDINACEL" : "Medinaceli , Soria ",
"SMinana"   : "Sierra de Minana , Soria ",
"SMINANA"   : "Sierra de Minana , Soria ",
"AVX909"    : "Garray experimental , Soria ",
"SSalvador" : "San Salvador, el Cuculo, Huesca ",
"SSALVADOR" : "San Salvador, el Cuculo, Huesca ",
"RINCONCIE" : "Cerler Sky Station, Huesca ",
"Rinconcie" : "Cerler Sky Station, Huesca ",
"Girolibre" : "Ainsa, Huesca ",
"GIROLIBRE" : "Ainsa, Huesca ",
"Aljarafe"  : "La Juliana, LEJI Sevilla ",
"ALJARAFE"  : "La Juliana, LEJI Sevilla ",
"LUGA"      : "LUGA Sevilla ",
"MSAG"      : "MSAG Malaga ",
"FAEPARAP"  : "Parapente Jaen ",
"Jaen"      : "Parapente Jaen ",
"PicAguila" : "Pico del Aguila, Huesca ",
"PICAGUILA" : "Pico del Aguila, Huesca ",
"LaRaca"    : "LA Raca, Huesca ",
"LARACA"    : "LA Raca, Huesca ",
"FISCAL"    : "Fiscal, Huesca ",
"CHISTAU"   : "Plan, Huesca ",
"Chistau"   : "Plan, Huesca ",
"LASPUNA"   : "Laspuña, Huesca ",
"Laspuna"   : "Laspuña, Huesca ",
"Panticosa" : "Panticosa, Huesca ",
"PANTICOSA" : "Panticosa, Huesca ",
"Benidorm1" : "Benidorm, Alicante ",
"BENIDORM1" : "Benidorm, Alicante ",
"Benidorm2" : "Benidorm, Alicante ",
"BENIDORM2" : "Benidorm, Alicante ",
"Pegalajar" : "Pegalajar, Jaen ",
"PEGALAJAR" : "Pegalajar, Jaen ",
"ElYelmo"   : "El Yelmo, Jaen ",
"ELYELMO"   : "El Yelmo, Jaen ",
"Avila"     : "Avila ",
"Viados"    : "Refugio Viados ",
"Montsec"   : "Ager Monstsec, Lerida ",
"MONTSEC"   : "Ager Monstsec, Lerida ",
"TorDlOrri" : "Torreta del Orri, Lerida ",
"TORDLORRI" : "Torreta del Orri, Lerida ",
"Baqueira"  : "Cap de Baqueira, Lerida ",
"BAQUEIRA"  : "Cap de Baqueira, Lerida ",
"BoiTaull"  : "Boi Taull, Lerida ",
"BOITAULL"  : "Boi Taull, Lerida ",
"Lillo"     : "Lillo, Toledo ",
"ARANGOITI" : "Arangoiti, Navarra ",
"ELPUERTO"  : "El Puerto de Santa Maria, Cadiz ",
"ElPuerto"  : "El Puerto de Santa Maria, Cadiz ",
"ABDALAJIS" : "Valle de Abdalajis, Malaga ",
"AXARQUIA"  : "Valle de la Axarquia, Malaga ",
"SSCC-RDAR" : "Estacion radar Paracuellos, Madrid ",
"SPAINAVX"  : "Estacion ficticia gateway AVX ",
"SPAINTTT"  : "Estacion ficticia gateway Enaire ",
"SPAINENA"  : "Estacion ficticia gateway Enaire ",

# french airports
"LFBM"   : "Mont de Marsan",
"LFBA"   : "La Garomme", 
"LFBS"   : "Biscarrosse", 
"LFCO"   : "Oloron",
"LFCX"   : "Moissac ", 
"LFCG"   : "Saint Girons", 
"LFCH"   : "Arcachon", 
"LFCB"   : "Bagneres de Luchon",
"LFCQ"   : "Graulhet",
"LFCS"   : "Bordeaux", 
"LFDT"   : "Tarbes",
"LFDA"   : "Air sur Adour",
"LFDA2"  : "Air sur Adour",
"LFDH"   : "Auch",
"LFDT2"  : "Tarbes",
"LFIM"   : "Saint Gaudens",
"LFNW"   : "Puivert",
"LFNW2"  : "Puivert",
"LFNQ"   : "Mount-Louis",
"LFNQ2"  : "Mount-Louis",
"LFDHTWR": "Auch",
"LFID"   : "Condom/Valence",
"LFCN"   : "Novaro",
"LFIT"   : "Toulouse Bourg",
"LFIL"   : "Rion des Landes",
"LFNB"   : "Mende",
"LFNE"   : "Salon Eyguires",
"LFNL"   : "Saint Martin",
"LFNZ"   : "Romanin-Saint Remy",
"LFNT"   : "Avignon-Pujaut ", 
"LFMP"   : "Perpignan", 
"LFMG"   : "La Montagne Noir", 
"LFMP"   : "Perpignan", 
"LFIX"   : "Itxassou", 
"LFLE"   : "Challes les Eaux", 
"LFDM"   : "Marmande", 
"PAU"    : "Pau",
"ROCAUDE": "Les Angles Ski Station",
"POUBEAU": "Pou Beau, France",
"BRAM"   : "Puivert test",
"CARCA"  : "Carcassone, France",
"ROQUEFORT" : "Roquefort, France",
"Roquefort" : "Roquefort, France",
"FONTROMEU" : "FontRomeu, France ",
"FontRomeu" : "FontRomeu, France ",
# Portuguese airports
           "LPCB"      : "Castelo Branco",
           "LPMU"      : "Modadouro ",
           "LPLZ"      : "Lousa",
           "LPMN"      : "Amondoeira",
           "LPEV"      : "Evora",
           "LPVZ"      : "Viseu",
           "BELAVISTA" : "Belavista, Lisbon ",
# Chilean airports 
           "SCLC"      : "Vitacura Municipal ",
           "SCVH"      : "Chacabuco Municipal ",
           "VITACURA1" : "Vitacura - 1 ",
           "VITACURA2" : "Vitacura - 2 ",
           "COLORADO"  : "Colorado ski resort  ",
           "WBUXTON"   : "Chicureo area - 1 ",
           "WBUXTON2"  : "Chicureo area - 2 ",
           "ROBLE1"    : "El Roble hill - 1",
           "ROBLE2"    : "El Roble hill - 2",
           "ROBLE3"    : "El Roble hill - 3",
           "ROBLE4"    : "El Roble hill - 4",
           "LOSANDES1" : "Los andes area - 1 ",
           "LOSANDES2" : "Los andes area - 2 ",
           "TROCALAN1" : "Trocalan hill - 1", 
           "TROCALAN2" : "Trocalan hill - 2", 
           "PoloCL"    : "Polo field",
           "ELBOSQUE1" : "El Bosque Airfield",
           "ELBOSQUE2" : "El Bosque Airfield",
           "ALFALFAL"  : "Alfalfal hidroelectic plant",
           "PUNTILLA"  : "Alfalfal hill",
           "SANRAMON1" : "San Ramon Mountain 1",
           "SANRAMON2" : "San Ramon Mountain 2",
           "SANRAMON3" : "San Ramon Mountain 3",
           "OLMUE"     : "OLMUE Airfield",
# -------------------------------------------------------------------#
# ------------------------------------------------------------------ #
	}
# -------------------------------------------------------------------#
