
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#Check if you have the good Vagrant version to use docker provider...
Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "APRSLOG"
  end

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  #config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./data", "/vagrant_data"

  #config.vm.synced_folder "./public", "/var/www/public"
  #config.vm.synced_folder "./html",   "/var/www/html"
  #config.vm.synced_folder "/nfs",   "/nfs"
  #config.vm.synced_folder "/oldnfs",   "/oldnfs"
  #config.vm.synced_folder "/bkups",   "/bkups"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.hostname = "vagrant-docker"
  config.vm.provider "docker" do |d|
    d.has_ssh = true
    d.build_dir = "."
    d.remains_running = false
    d.cmd = ["tail", "-f", "/dev/null"]
  end
  config.vm.network "forwarded_port", guest: 80, host: 8585
  config.ssh.insert_key = false
  config.ssh.private_key_path = [
    '~/.ssh/id_rsa',
    '~/.vagrant.d/insecure_private_key'
  ]
  config.vm.provision 'file', 
    source: '~/.ssh/id_rsa.pub', 
    destination: '~/.ssh/authorized_keys'
  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"
  #config.ssh.private_key_path = ["#{ENV['HOME']}/.ssh/id_rsa"]
  #
  # View the documentation for the provider you're using for more
  # information on available options.

end


